use crate::HashAlg;
use crate::multihash::MultihashDigest;
use malt::{Log, TreeHasher};
use std::collections::BTreeMap;

/// A multi-algorithm hasher for the Cyphrpass MALT implementation.
/// Computes digests for all configured active algorithms simultaneously,
/// ensuring that each log node is a valid `MultihashDigest`.
#[derive(Clone, Debug)]
pub struct CyphrpassMultiHasher {
    active_algs: Vec<HashAlg>,
}

impl CyphrpassMultiHasher {
    pub fn new(active_algs: Vec<HashAlg>) -> Self {
        Self { active_algs }
    }
}

impl TreeHasher for CyphrpassMultiHasher {
    type Digest = MultihashDigest;

    fn leaf(&self, data: &[u8]) -> Self::Digest {
        // H(0x00 || data)
        let mut prefix_data = Vec::with_capacity(1 + data.len());
        prefix_data.push(0x00);
        prefix_data.extend_from_slice(data);

        let mut map = BTreeMap::new();
        for &alg in &self.active_algs {
            let digest = crate::state::hash_bytes(alg, &prefix_data);
            map.insert(alg, digest.into_boxed_slice());
        }
        MultihashDigest::new(map).expect("Empty active algorithms not allowed in MALT hasher")
    }

    fn node(&self, left: &Self::Digest, right: &Self::Digest) -> Self::Digest {
        // For each algorithm, compute H(0x01 || left_digest || right_digest)
        let mut map = BTreeMap::new();
        for &alg in &self.active_algs {
            // Because left and right were generated by this same hasher,
            // they must contain digests for all active_algs.
            let l_dig = left
                .get(alg)
                .expect("Invariant violation: left node missing algorithm digest");
            let r_dig = right
                .get(alg)
                .expect("Invariant violation: right node missing algorithm digest");

            let mut d = Vec::with_capacity(1 + l_dig.len() + r_dig.len());
            d.push(0x01);
            d.extend_from_slice(l_dig);
            d.extend_from_slice(r_dig);

            let digest = crate::state::hash_bytes(alg, &d);
            map.insert(alg, digest.into_boxed_slice());
        }
        MultihashDigest::new(map).expect("Empty active algorithms not allowed in MALT hasher")
    }

    fn empty(&self) -> Self::Digest {
        // H("")
        let mut map = BTreeMap::new();
        for &alg in &self.active_algs {
            let digest = crate::state::hash_bytes(alg, b"");
            map.insert(alg, digest.into_boxed_slice());
        }
        MultihashDigest::new(map).expect("Empty active algorithms not allowed in MALT hasher")
    }
}

/// The Commit Root represents the finalized state of the verifiable MALT log.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommitRoot(pub MultihashDigest);

impl CommitRoot {
    pub fn as_multihash(&self) -> &MultihashDigest {
        &self.0
    }
}

pub type CommitLog = Log<CyphrpassMultiHasher>;

/// Compute the Commit Root incrementally over a list of TRs.
pub fn compute_cr(trs: &[&MultihashDigest], algs: &[HashAlg]) -> crate::error::Result<CommitRoot> {
    let hasher = CyphrpassMultiHasher::new(algs.to_vec());
    let mut log = Log::new(hasher);

    for tr in trs {
        // Concatenate the digests of all active algorithms deterministically
        let mut bytes = Vec::new();
        for &alg in algs {
            bytes.extend_from_slice(tr.get(alg).unwrap_or(&[]));
        }
        log.append(&bytes);
    }

    Ok(CommitRoot(log.root()))
}
