[package]
edition = "2024"
name    = "cyphr-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
coz           = { workspace = true }
libfuzzer-sys = "0.4"
serde_json    = { workspace = true }
tokio         = { workspace = true, features = ["rt", "macros"] }

[dependencies.cyphr]
path = "../cyphr"

[dependencies.cyphr-storage]
path = "../cyphr-storage"

[[bin]]
bench = false
doc   = false
name  = "fuzz_coz_parser"
path  = "fuzz_targets/fuzz_coz_parser.rs"
test  = false

[[bin]]
bench = false
doc   = false
name  = "fuzz_reindex"
path  = "fuzz_targets/fuzz_reindex.rs"
test  = false
