package testfixtures

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Golden is a pre-computed test case with real cryptographic values.
//
// Golden files are generated by the Rust test-fixtures crate and contain
// all information needed to verify the Go implementation produces identical
// results.
type Golden struct {
	// Name is the test identifier.
	Name string `json:"name"`
	// Principal lists genesis key names from the pool.
	Principal []string `json:"principal"`
	// Setup contains optional modifiers (e.g., pre-revoke keys).
	Setup *GoldenSetup `json:"setup,omitempty"`
	// GenesisKeys contains full key material for storage import.
	GenesisKeys []GoldenKey `json:"genesis_keys,omitempty"`
	// Commits contains atomic transaction bundles (new format).
	Commits []GoldenCommit `json:"commits,omitempty"`
	// Entries contains storage-format entries (legacy format, deprecated).
	Entries []json.RawMessage `json:"entries,omitempty"`
	// Digests contains czd values parallel to entries.
	Digests []string `json:"digests,omitempty"`
	// Expected contains assertions about final state.
	Expected GoldenExpected `json:"expected"`
}

// GoldenSetup contains setup modifiers for a test.
type GoldenSetup struct {
	// RevokeKey is a key name to pre-revoke before test.
	RevokeKey string `json:"revoke_key,omitempty"`
	// RevokeAt is the timestamp for the revocation.
	RevokeAt int64 `json:"revoke_at,omitempty"`
}

// GoldenKey is key material embedded in a golden file.
type GoldenKey struct {
	// Alg is the algorithm.
	Alg string `json:"alg"`
	// Pub is the public key (base64url).
	Pub string `json:"pub"`
	// Tmb is the thumbprint (base64url).
	Tmb string `json:"tmb"`
}

// GoldenCommit is an atomic transaction bundle from a golden file.
// Matches the Rust fixture format: {txs, ts, as, ps}.
type GoldenCommit struct {
	// Txs contains the transactions in this commit.
	Txs []json.RawMessage `json:"txs"`
	// TS is the transaction state after this commit (base64url).
	TS string `json:"ts,omitempty"`
	// AS is the auth state after this commit (base64url).
	AS string `json:"as,omitempty"`
	// PS is the principal state after this commit (base64url).
	PS string `json:"ps,omitempty"`
}

// GoldenExpected contains expected state assertions.
type GoldenExpected struct {
	// KeyCount is the expected number of active keys.
	KeyCount *int `json:"key_count,omitempty"`
	// Level is the expected feature level.
	Level *int `json:"level,omitempty"`
	// KS is the expected key state digest.
	KS string `json:"ks,omitempty"`
	// AS is the expected auth state digest (JSON field is "as").
	AS string `json:"as,omitempty"`
	// PS is the expected principal state digest.
	PS string `json:"ps,omitempty"`
	// TS is the expected transaction state digest.
	TS string `json:"ts,omitempty"`
	// DS is the expected data state digest.
	DS string `json:"ds,omitempty"`
	// PR is the expected principal root.
	PR string `json:"pr,omitempty"`
	// Error is the expected error (for error tests).
	Error string `json:"error,omitempty"`
}

// LoadGolden loads a golden test from a JSON file.
func LoadGolden(path string) (*Golden, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read golden file: %w", err)
	}

	var golden Golden
	if err := json.Unmarshal(data, &golden); err != nil {
		return nil, fmt.Errorf("failed to parse golden JSON: %w", err)
	}

	return &golden, nil
}

// LoadGoldenDir loads all golden tests from a directory.
func LoadGoldenDir(dir string) ([]*Golden, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("failed to read golden directory: %w", err)
	}

	var goldens []*Golden
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		path := filepath.Join(dir, entry.Name())
		golden, err := LoadGolden(path)
		if err != nil {
			return nil, fmt.Errorf("failed to load %s: %w", entry.Name(), err)
		}
		goldens = append(goldens, golden)
	}

	return goldens, nil
}

// IsGenesisOnly returns true if this test has no transactions.
func (g *Golden) IsGenesisOnly() bool {
	return len(g.Commits) == 0 && len(g.Entries) == 0
}

// IsErrorTest returns true if this test expects an error.
func (g *Golden) IsErrorTest() bool {
	return g.Expected.Error != ""
}

// EntryCount returns the number of entries (from commits or legacy entries).
func (g *Golden) EntryCount() int {
	if len(g.Commits) > 0 {
		count := 0
		for _, c := range g.Commits {
			count += len(c.Txs)
		}
		return count
	}
	return len(g.Entries)
}

// FlattenEntries returns all transaction entries from commits or legacy entries.
func (g *Golden) FlattenEntries() []json.RawMessage {
	if len(g.Commits) > 0 {
		var entries []json.RawMessage
		for _, c := range g.Commits {
			entries = append(entries, c.Txs...)
		}
		return entries
	}
	return g.Entries
}
