package testfixtures

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Golden is a pre-computed test case with real cryptographic values.
//
// Golden files are generated by the Rust test-fixtures crate and contain
// all information needed to verify the Go implementation produces identical
// results.
type Golden struct {
	// Name is the test identifier.
	Name string `json:"name"`
	// Principal lists genesis key names from the pool.
	Principal []string `json:"principal"`
	// Setup contains optional modifiers (e.g., pre-revoke keys).
	Setup *GoldenSetup `json:"setup,omitempty"`
	// GenesisKeys contains full key material for storage import.
	GenesisKeys []GoldenKey `json:"genesis_keys,omitempty"`
	// Commits contains atomic transaction bundles.
	Commits []GoldenCommit `json:"commits,omitempty"`
	// Digests contains czd values parallel to entries.
	Digests []string `json:"digests,omitempty"`
	// Expected contains assertions about final state.
	Expected GoldenExpected `json:"expected"`
}

// GoldenSetup contains setup modifiers for a test.
type GoldenSetup struct {
	// RevokeKey is a key name to pre-revoke before test.
	RevokeKey string `json:"revoke_key,omitempty"`
	// RevokeAt is the timestamp for the revocation.
	RevokeAt int64 `json:"revoke_at,omitempty"`
}

// GoldenKey is key material embedded in a golden file.
type GoldenKey struct {
	// Alg is the algorithm.
	Alg string `json:"alg"`
	// Pub is the public key (base64url).
	Pub string `json:"pub"`
	// Tmb is the thumbprint (base64url).
	Tmb string `json:"tmb"`
	// Tag is an optional human-readable label.
	Tag string `json:"tag,omitempty"`
	// Now is an optional creation timestamp.
	Now int64 `json:"now,omitempty"`
}

// GoldenCommit is an atomic transaction bundle from a golden file.
// Matches the Rust fixture format: {txs, keys, commit_id, ar, cs, pr}.
type GoldenCommit struct {
	// Txs contains the transactions in this commit.
	Txs []json.RawMessage `json:"txs"`
	// Keys contains key material introduced in this commit (SPEC §5.2/§5.3).
	Keys []GoldenKey `json:"keys"`
	// CommitID is the commit identity after this commit (base64url).
	CommitID string `json:"commit_id,omitempty"`
	// AR is the auth root after this commit (base64url).
	AR string `json:"ar,omitempty"`
	// CS is the commit state after this commit (base64url).
	CS string `json:"cs,omitempty"`
	// PR is the principal root after this commit (base64url).
	PR string `json:"pr,omitempty"`
}

// GoldenExpected contains expected state assertions.
type GoldenExpected struct {
	// KeyCount is the expected number of active keys.
	KeyCount *int `json:"key_count,omitempty"`
	// Level is the expected feature level.
	Level *int `json:"level,omitempty"`
	// KR is the expected key root digest (first variant).
	KR string `json:"kr,omitempty"`
	// AR is the expected auth root digest (first variant).
	AR string `json:"ar,omitempty"`
	// PR is the expected principal root digest (first variant).
	PR string `json:"pr,omitempty"`
	// CommitID is the expected commit ID digest.
	CommitID string `json:"commit_id,omitempty"`
	// TS is a backwards-compatible alias for CommitID (legacy golden files).
	TS string `json:"ts,omitempty"`
	// CS is the expected commit state digest.
	CS string `json:"cs,omitempty"`
	// DR is the expected data root digest.
	DR string `json:"dr,omitempty"`
	// PG is the expected principal genesis.
	PG string `json:"pg,omitempty"`
	// Error is the expected error (for error tests).
	Error string `json:"error,omitempty"`
	// MultihashKR contains per-algorithm KR variants for cross-impl verification (SPEC §14).
	MultihashKR map[string]string `json:"multihash_kr,omitempty"`
	// MultihashAR contains per-algorithm AR variants for cross-impl verification.
	MultihashAR map[string]string `json:"multihash_ar,omitempty"`
	// MultihashPR contains per-algorithm PR variants for cross-impl verification.
	MultihashPR map[string]string `json:"multihash_pr,omitempty"`
}

// LoadGolden loads a golden test from a JSON file.
func LoadGolden(path string) (*Golden, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read golden file: %w", err)
	}

	var golden Golden
	if err := json.Unmarshal(data, &golden); err != nil {
		return nil, fmt.Errorf("failed to parse golden JSON: %w", err)
	}

	return &golden, nil
}

// LoadGoldenDir loads all golden tests from a directory.
func LoadGoldenDir(dir string) ([]*Golden, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("failed to read golden directory: %w", err)
	}

	var goldens []*Golden
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		path := filepath.Join(dir, entry.Name())
		golden, err := LoadGolden(path)
		if err != nil {
			return nil, fmt.Errorf("failed to load %s: %w", entry.Name(), err)
		}
		goldens = append(goldens, golden)
	}

	return goldens, nil
}

// IsGenesisOnly returns true if this test has no transactions.
func (g *Golden) IsGenesisOnly() bool {
	return len(g.Commits) == 0
}

// IsErrorTest returns true if this test expects an error.
func (g *Golden) IsErrorTest() bool {
	return g.Expected.Error != ""
}

// TxCount returns the total number of transactions across all commits.
func (g *Golden) TxCount() int {
	count := 0
	for _, c := range g.Commits {
		count += len(c.Txs)
	}
	return count
}
