package testfixtures

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Golden is a pre-computed test case with real cryptographic values.
//
// Golden files are generated by the Rust test-fixtures crate and contain
// all information needed to verify the Go implementation produces identical
// results.
type Golden struct {
	// Name is the test identifier.
	Name string `json:"name"`
	// Principal lists genesis key names from the pool.
	Principal []string `json:"principal"`
	// Setup contains optional modifiers (e.g., pre-revoke keys).
	Setup *GoldenSetup `json:"setup,omitempty"`
	// GenesisKeys contains full key material for storage import.
	GenesisKeys []GoldenKey `json:"genesis_keys,omitempty"`
	// Commits contains atomic transaction bundles.
	Commits []GoldenCommit `json:"commits,omitempty"`
	// Digests contains czd values parallel to entries.
	Digests []string `json:"digests,omitempty"`
	// Expected contains assertions about final state.
	Expected GoldenExpected `json:"expected"`
}

// GoldenSetup contains setup modifiers for a test.
type GoldenSetup struct {
	// RevokeKey is a key name to pre-revoke before test.
	RevokeKey string `json:"revoke_key,omitempty"`
	// RevokeAt is the timestamp for the revocation.
	RevokeAt int64 `json:"revoke_at,omitempty"`
}

// GoldenKey is key material embedded in a golden file.
type GoldenKey struct {
	// Alg is the algorithm.
	Alg string `json:"alg"`
	// Pub is the public key (base64url).
	Pub string `json:"pub"`
	// Tmb is the thumbprint (base64url).
	Tmb string `json:"tmb"`
	// Tag is an optional human-readable label.
	Tag string `json:"tag,omitempty"`
	// Now is an optional creation timestamp.
	Now int64 `json:"now,omitempty"`
}

// GoldenCommit is an atomic transaction bundle from a golden file.
// Matches the Rust fixture format: {txs, keys, commit_id, as, cs, ps}.
type GoldenCommit struct {
	// Txs contains the transactions in this commit.
	Txs []json.RawMessage `json:"txs"`
	// Keys contains key material introduced in this commit (SPEC §5.2/§5.3).
	Keys []GoldenKey `json:"keys"`
	// CommitID is the commit identity after this commit (base64url).
	CommitID string `json:"commit_id,omitempty"`
	// AS is the auth state after this commit (base64url).
	AS string `json:"as,omitempty"`
	// CS is the commit state after this commit (base64url).
	CS string `json:"cs,omitempty"`
	// PS is the principal state after this commit (base64url).
	PS string `json:"ps,omitempty"`
}

// GoldenExpected contains expected state assertions.
type GoldenExpected struct {
	// KeyCount is the expected number of active keys.
	KeyCount *int `json:"key_count,omitempty"`
	// Level is the expected feature level.
	Level *int `json:"level,omitempty"`
	// KS is the expected key state digest (first variant).
	KS string `json:"ks,omitempty"`
	// AS is the expected auth state digest (JSON field is "as", first variant).
	AS string `json:"as,omitempty"`
	// PS is the expected principal state digest (first variant).
	PS string `json:"ps,omitempty"`
	// CommitID is the expected commit ID digest.
	CommitID string `json:"commit_id,omitempty"`
	// TS is a backwards-compatible alias for CommitID (legacy golden files).
	TS string `json:"ts,omitempty"`
	// CS is the expected commit state digest.
	CS string `json:"cs,omitempty"`
	// DS is the expected data state digest.
	DS string `json:"ds,omitempty"`
	// PR is the expected principal root.
	PR string `json:"pr,omitempty"`
	// Error is the expected error (for error tests).
	Error string `json:"error,omitempty"`
	// MultihashKS contains per-algorithm KS variants for cross-impl verification (SPEC §14).
	MultihashKS map[string]string `json:"multihash_ks,omitempty"`
	// MultihashAS contains per-algorithm AS variants for cross-impl verification.
	MultihashAS map[string]string `json:"multihash_as,omitempty"`
	// MultihashPS contains per-algorithm PS variants for cross-impl verification.
	MultihashPS map[string]string `json:"multihash_ps,omitempty"`
}

// LoadGolden loads a golden test from a JSON file.
func LoadGolden(path string) (*Golden, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read golden file: %w", err)
	}

	var golden Golden
	if err := json.Unmarshal(data, &golden); err != nil {
		return nil, fmt.Errorf("failed to parse golden JSON: %w", err)
	}

	return &golden, nil
}

// LoadGoldenDir loads all golden tests from a directory.
func LoadGoldenDir(dir string) ([]*Golden, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("failed to read golden directory: %w", err)
	}

	var goldens []*Golden
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		path := filepath.Join(dir, entry.Name())
		golden, err := LoadGolden(path)
		if err != nil {
			return nil, fmt.Errorf("failed to load %s: %w", entry.Name(), err)
		}
		goldens = append(goldens, golden)
	}

	return goldens, nil
}

// IsGenesisOnly returns true if this test has no transactions.
func (g *Golden) IsGenesisOnly() bool {
	return len(g.Commits) == 0
}

// IsErrorTest returns true if this test expects an error.
func (g *Golden) IsErrorTest() bool {
	return g.Expected.Error != ""
}

// TxCount returns the total number of transactions across all commits.
func (g *Golden) TxCount() int {
	count := 0
	for _, c := range g.Commits {
		count += len(c.Txs)
	}
	return count
}

// FlattenTxs returns all transaction entries from all commits.
func (g *Golden) FlattenTxs() []json.RawMessage {
	var txs []json.RawMessage
	for _, c := range g.Commits {
		txs = append(txs, c.Txs...)
	}
	return txs
}

// FlattenTxsWithKeys returns all transaction entries from all commits,
// with commit-level keys re-injected into key-introducing transactions.
//
// The Go storage layer reads key material from per-entry embedded "key"
// fields (Entry.KeyJSON()). Since keys are now stored at commit level,
// this method re-injects them before flattening so the storage layer
// can consume them without modification.
func (g *Golden) FlattenTxsWithKeys() ([]json.RawMessage, error) {
	var txs []json.RawMessage
	for _, c := range g.Commits {
		keyIdx := 0
		for _, tx := range c.Txs {
			// Check if this tx is key-introducing
			typ, err := extractTyp(tx)
			if err != nil {
				txs = append(txs, tx)
				continue
			}

			if isKeyIntroducing(typ) && keyIdx < len(c.Keys) {
				// Re-inject key into tx JSON
				injected, err := injectKey(tx, c.Keys[keyIdx])
				if err != nil {
					return nil, fmt.Errorf("inject key into tx: %w", err)
				}
				txs = append(txs, injected)
				keyIdx++
			} else {
				txs = append(txs, tx)
			}
		}
	}
	return txs, nil
}

// extractTyp extracts pay.typ from a raw JSON transaction.
func extractTyp(tx json.RawMessage) (string, error) {
	var extractor struct {
		Pay struct {
			Typ string `json:"typ"`
		} `json:"pay"`
	}
	if err := json.Unmarshal(tx, &extractor); err != nil {
		return "", err
	}
	return extractor.Pay.Typ, nil
}

// isKeyIntroducing returns true if the transaction type introduces new key material.
func isKeyIntroducing(typ string) bool {
	for i := 0; i+11 <= len(typ); i++ {
		if typ[i:i+11] == "/key/create" {
			return true
		}
	}
	for i := 0; i+12 <= len(typ); i++ {
		if typ[i:i+12] == "/key/replace" {
			return true
		}
	}
	return false
}

// injectKey embeds a GoldenKey into a raw JSON transaction as a "key" field.
func injectKey(tx json.RawMessage, key GoldenKey) (json.RawMessage, error) {
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(tx, &obj); err != nil {
		return nil, err
	}

	keyJSON, err := json.Marshal(map[string]any{
		"alg": key.Alg,
		"pub": key.Pub,
		"tmb": key.Tmb,
	})
	if err != nil {
		return nil, err
	}

	obj["key"] = keyJSON
	return json.Marshal(obj)
}

// FlattenTxsWithBoundaries returns all transaction entries and the indices
// of commit finalizer transactions (last tx of each commit).
func (g *Golden) FlattenTxsWithBoundaries() (txs []json.RawMessage, finalizerIndices []int) {
	idx := 0
	for _, c := range g.Commits {
		for i, tx := range c.Txs {
			txs = append(txs, tx)
			// Last tx in this commit is the finalizer
			if i == len(c.Txs)-1 {
				finalizerIndices = append(finalizerIndices, idx)
			}
			idx++
		}
	}
	return txs, finalizerIndices
}
